tntRandomRange -1.0
stackableShulkerBoxes 16
renewableCoral true
tntPrimerMomentumRemoved true
xpNoCooldown true
language zh_cn
smoothClientAnimations true
renewableDeepslate true
allowSpawningOfflinePlayers true
explosionNoBlockDamage false
movableAmethyst true
fastRedstoneDust true
rotatorBlock false
renewableBlackstone true
xpFromExplosions true
antiCheatDisabled true
desertShrubs true
optimizedTNT true
mergeTNT false
placementRotationFix true
lagFreeSpawning true
viewDistance 12
movableBlockEntities true
